--[[
	@notes: 
	-@hexadecival: handle drawlist and components more efficiently
	-@hexadecival: handle tilemap system differently (use voxel system wen waffle makes it)
	-@hexadecival: solve colissions and implement gravity + jumping for player
	-@hexadecival: ?work on networking backend?
	-@hexadecival: implement rotations and scaling
	-@hexadecival: UI backend / classes
	-@hexadecival: create some particle system for A E S T E T H I C S
	-@hexadecival: implement spritesheet system and more efficient image-related memory handling
	-@hexadecival: create animation framework and necessary classes for it
	-@hexadecival: create raycasting algorithm
--]]